AWSTemplateFormatVersion: 2010-09-09

Description: Template to create an EC2 instance and enable SSH

Parameters: 
  KeyName:
      Description: Name of SSH KeyPair
      Type: 'AWS::EC2::KeyPair::KeyName'
      ConstraintDescription: Provide the name of an existing SSH key pair
  InstanceName:
      Description: Instance Name
      Type: String
  SubnetId:
      Description: Subnet ID
      Type: String
  VpcId:
      Description: Instance Name
      Type: String
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: !FindInMap [ RegionMap, !Ref 'AWS::Region', HVM64 ]
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
       - !GetAtt InstanceSecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: !Ref InstanceName
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

Mappings: 
  RegionMap: 
    us-east-1: 
      "HVM64": "ami-0ff8a91507f77f867"
    us-west-1: 
      "HVM64": "ami-0bdb828fd58c52235"
    eu-west-1: 
      "HVM64": "ami-047bb4163c506cd98"
    ap-southeast-1: 
      "HVM64": "ami-08569b978cc4dfa10"
    ap-northeast-1: 
      "HVM64": "ami-06cd52961ce9f0d85"

Outputs: 
  InstanceID:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
